### ISSUE TITLE
Chinese characters cause alignment problems

### ISSUE THREAD

**Issue by brickmill** [Electrux/ls_extended#11]
Thanks for making this project! I just found a little bug:

![extended](https://user-images.githubusercontent.com/38190282/41336268-0ebccbe2-6eec-11e8-9f9d-0f8423f33485.png)

I'm using [termite](https://github.com/thestinger/termite/) as my terminal.

**Comment by MaT1g3R** [comment]
I am having the same issue

**Comment by Chirag-Khandelwal** [comment]
ok i think i know the reason. The UTF characters take more than 1 byte and hence, if we display them on screen, we have to add the padding columns with the number of extra bytes to compensate and hence display the columns correctly.
However, for chinese characters, each character takes the space on screen - equivalent of 2 normal english characters and hence the column fails to compensate correctly, thereby adding extra columns and hence making it look like the screen shot above

**Comment by Chirag-Khandelwal** [comment]
The chinese characters should be fixed now. Could you guys test please?

**Comment by MaT1g3R** [comment]
It seems like it still have some problems :(

![screen shot 2018-06-16 at 2 11 09 pm](https://user-images.githubusercontent.com/15258494/41496308-35fd6704-716f-11e8-9563-a98f3a2b8b59.png)

**Comment by Chirag-Khandelwal** [comment]
those are japanese or korean characters right?

**Comment by MaT1g3R** [comment]
Those are Japanese characters

**Comment by gatlee** [comment]
https://stackoverflow.com/questions/3634627/how-to-know-the-preferred-display-width-in-columns-of-unicode-characters This should help with calculating padding

**Comment by brickmill** [comment]
Chinese characters seem to be working for me. Thanks!

**Comment by gatlee** [comment]
I think https://stackoverflow.com/questions/3634627/how-to-know-the-preferred-display-width-in-columns-of-unicode-characters would help fix this easily without having to manually search for languages with double spacing. I'll have a pull request up soon

**Comment by Chirag-Khandelwal** [comment]
ok i made some changes... please see if this works now?

**Comment by MaT1g3R** [comment]
It still doesn't work :(

Here is the file list if you want to do some testing:

https://dpaste.de/o42x

![screen shot 2018-06-16 at 8 09 32 pm](https://user-images.githubusercontent.com/15258494/41498467-3f79e3de-71a1-11e8-8f37-9a75e04ed8e0.png)

**Comment by gatlee** [comment]
https://github.com/termux/wcwidth
I think this might work better than the other one which was updated in 2001. Seems to be a lot more comprehensive

**Comment by gatlee** [comment]
I have a potential fix that I'm working on. I think it should work

**Comment by Chirag-Khandelwal** [comment]
oh that's amazing! i eagerly await it. I am also trying to find a fix myself in the meantime :)

**Comment by Chirag-Khandelwal** [comment]
Updated the codebase to version 1.0.7. It should have support for much greater range of full width characters. Could you guys please try it?

**Comment by MaT1g3R** [comment]
It is still not working correctly 😢

**Comment by Chirag-Khandelwal** [comment]
ok i used the list of files u gave me and was able to find the character sets responsible. According to your file list, it should now work from version 1.0.8 😄

**Comment by Chirag-Khandelwal** [comment]
Please use it and see if it works correctly :)

**Comment by MaT1g3R** [comment]
It is fixed! Thank you so much

**Comment by Chirag-Khandelwal** [comment]
Awesome! Thanks a lot :D
